; LocalDictionary.ahk — the bundled offline dictionary (WordNet 3.1).
;
; Why this exists: looking a word up used to mean an HTTPS request per unseen
; word. A desktop dictionary has no business needing a network, and every
; request is one more thing the user has to trust. The whole dictionary now
; ships inside the program.
;
; The data is assets\dictionary.dat, generated by scripts\build-dictionary.ps1:
; one tab-separated record per line, sorted by key. It is never loaded into a
; Map — 86k entries would cost far more memory than a tray app should take.
; Instead the sorted bytes are searched in place, so a lookup touches a handful
; of cache lines and the resident cost is the file itself.
;
; In a compiled build the bytes are a resource inside the .exe (so the portable
; build stays a single file and nothing is written to disk); when running from
; source they are read from assets\.
#Requires AutoHotkey v2.0

class LocalDictionary {
    static _ptr := 0        ; address of the first byte of the data
    static _size := 0       ; length in bytes
    static _buf := ""       ; keeps the dev-run Buffer alive; unused when compiled
    static _tried := false  ; load attempted (success or not) — do not retry per word

    ; Morphy's suffix-detachment rules. Irregular forms ("ran", "mice") are
    ; redirect records in the data file; these rules cover the regular ones for
    ; free, which is why the file does not carry millions of inflections.
    ; Longest suffixes first: "ponies" must hit "ies"->"y" before "s"->"".
    static _rules := [["ches", "ch"], ["shes", "sh"], ["ses", "s"], ["xes", "x"]
                    , ["zes", "z"], ["ies", "y"], ["men", "man"], ["ing", ""]
                    , ["ing", "e"], ["est", ""], ["est", "e"], ["ed", ""]
                    , ["ed", "e"], ["es", ""], ["es", "e"], ["er", ""]
                    , ["er", "e"], ["s", ""]]

    ; True once the data is available. A build with no dictionary still runs —
    ; it just has nothing to answer with until the online fallback is enabled.
    static Available() {
        if !LocalDictionary._tried
            LocalDictionary._Load()
        return LocalDictionary._size > 0
    }

    ; Returns { word, pos, def, alt, example } for a hit, or "" for a miss.
    ; `word` is the entry actually found, which for an inflected form is the
    ; base word ("ran" resolves to, and is shown as, "run").
    static Lookup(word) {
        if !LocalDictionary.Available()
            return ""

        key := StrLower(word)
        rec := LocalDictionary._Find(key)
        if (rec != "")
            return rec

        ; Not a headword — try to strip a regular inflection.
        for rule in LocalDictionary._rules {
            suffix := rule[1], repl := rule[2]
            if (StrLen(key) <= StrLen(suffix))
                continue
            if (SubStr(key, -StrLen(suffix)) != suffix)
                continue
            cand := SubStr(key, 1, StrLen(key) - StrLen(suffix)) . repl
            if (StrLen(cand) < 2)
                continue
            rec := LocalDictionary._Find(cand)
            if (rec != "")
                return rec
        }
        return ""
    }

    ; --- Loading -------------------------------------------------------------

    static _Load() {
        LocalDictionary._tried := true
        if A_IsCompiled
            LocalDictionary._LoadResource()
        else
            LocalDictionary._LoadFile(A_ScriptDir "\" Config.DictRelPath)
    }

    ; The compiled .exe carries the data as an RT_RCDATA resource (added by the
    ; Ahk2Exe directive in Main.ahk). LockResource hands back a pointer into the
    ; already-mapped image, so this copies nothing and allocates nothing.
    static _LoadResource() {
        static RT_RCDATA := 10
        try {
            hMod := DllCall("GetModuleHandle", "ptr", 0, "ptr")
            hRes := DllCall("FindResource", "ptr", hMod, "str", Config.DictResourceName
                          , "ptr", RT_RCDATA, "ptr")
            if !hRes
                return
            size := DllCall("SizeofResource", "ptr", hMod, "ptr", hRes, "uint")
            hGlob := DllCall("LoadResource", "ptr", hMod, "ptr", hRes, "ptr")
            if (!hGlob || !size)
                return
            ptr := DllCall("LockResource", "ptr", hGlob, "ptr")
            if !ptr
                return
            LocalDictionary._ptr := ptr
            LocalDictionary._size := size
        }
    }

    static _LoadFile(path) {
        if !FileExist(path)
            return
        try {
            buf := FileRead(path, "RAW")
            LocalDictionary._buf := buf        ; hold the reference: the pointer
            LocalDictionary._ptr := buf.Ptr    ; below is only valid while it lives
            LocalDictionary._size := buf.Size
        }
    }

    ; --- Search --------------------------------------------------------------

    ; Binary search over the byte range. Every line begins a record and the file
    ; is sorted by key, so the usual halving works on byte offsets as long as
    ; each probe is nudged forward to the next line boundary.
    static _Find(key) {
        ; The needle is compared byte by byte, so encode it once. Keys are ASCII
        ; (Config.WordPattern), but going through UTF-8 keeps the two sides
        ; honest if that ever widens.
        tBuf := Buffer(StrPut(key, "UTF-8"))
        tLen := StrPut(key, tBuf, "UTF-8") - 1     ; less the NUL StrPut appends

        ptr := LocalDictionary._ptr, size := LocalDictionary._size
        lo := 0, hi := size
        while (lo < hi) {
            mid := (lo + hi) // 2
            s := mid
            if (s > 0) {                            ; advance to a line start
                while (s < size && NumGet(ptr, s, "UChar") != 10)
                    s++
                s++
            }
            if (s >= hi) {
                hi := mid
                continue
            }
            if (LocalDictionary._Compare(ptr, s, tBuf.Ptr, tLen) < 0) {
                e := s
                while (e < size && NumGet(ptr, e, "UChar") != 10)
                    e++
                lo := e + 1                         ; whole line ruled out
            } else
                hi := mid
        }

        ; lo is a line start and the answer, if present, is at or just past it.
        ; The bound is paranoia: a corrupt file must not spin here.
        pos := lo
        loop 64 {
            if (pos >= size)
                return ""
            c := LocalDictionary._Compare(ptr, pos, tBuf.Ptr, tLen)
            e := pos
            while (e < size && NumGet(ptr, e, "UChar") != 10)
                e++
            if (c == 0)
                return LocalDictionary._Record(key, StrGet(ptr + pos, e - pos, "UTF-8"))
            if (c > 0)
                return ""                           ; past where it would be
            pos := e + 1
        }
        return ""
    }

    ; Ordinal comparison of the key at byte offset `at` against the needle.
    ; Ordinal on purpose: AHK's string operators compare case-insensitively and
    ; would not agree with the byte order the file was sorted in.
    static _Compare(ptr, at, tPtr, tLen) {
        i := 0
        loop {
            b := NumGet(ptr, at + i, "UChar")
            if (b == 9 || b == 10)                  ; tab or newline ends the key
                return (i >= tLen) ? 0 : -1
            if (i >= tLen)
                return 1
            t := NumGet(tPtr, i, "UChar")
            if (b != t)
                return (b < t) ? -1 : 1
            i++
        }
    }

    ; "key<TAB>pos<TAB>def<TAB>alt<TAB>example", or a redirect for an irregular
    ; form: "mice<TAB>=<TAB>mouse".
    static _Record(key, line) {
        f := StrSplit(RTrim(line, "`r"), "`t")
        if (f.Length < 2)
            return ""
        if (f[2] == "=") {
            ; One hop only. The generator never chains redirects, and refusing to
            ; follow a second one means a bad file cannot loop us.
            target := f.Length >= 3 ? f[3] : ""
            if (target == "" || target == key)
                return ""
            line2 := LocalDictionary._FindRaw(target)
            return line2 != "" ? line2 : ""
        }
        return { word: f[1]
               , pos: f[2]
               , def: f.Length >= 3 ? f[3] : ""
               , alt: f.Length >= 4 ? f[4] : ""
               , example: f.Length >= 5 ? f[5] : "" }
    }

    ; Resolves a redirect target, which by construction is a real entry.
    static _FindRaw(word) {
        rec := LocalDictionary._Find(word)
        return (rec != "" && rec.pos != "=") ? rec : ""
    }
}
